# Generated by Django 3.2 on 2023-06-23 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'restaurant', 'verbose_name_plural': 'restaurants'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09...' or format: '+989...", regex='^(\\+98|0)?9\\d{9}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurants',
        ),
    ]
