# Generated by Django 3.2 on 2023-06-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelTable(
            name='address',
            table='Addresses',
        ),
        migrations.AlterModelTable(
            name='city',
            table='Cities',
        ),
        migrations.AlterModelTable(
            name='country',
            table='Countries',
        ),
    ]
