# Generated by Django 3.2 on 2023-07-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20230709_1108'),
        ('orders', '0003_auto_20230709_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.menuitem', verbose_name='menu item'),
        ),
    ]
